set dotenv-load

# app version: 
#     flink run-application --target kubernetes-application \
#     -Dkubernetes.cluster-id=my-first-application-cluster \
#     -Dkubernetes.container.image.ref=swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/flink-newbie:{{version}} \
#     local:///opt/flink/usrlib/first-love-0.1.jar

origin: 
    flink run-application --target kubernetes-application \
    --class lake.BatchJob \
    -Dkubernetes.cluster-id=my-first-application-cluster \
    -Dkubernetes.container.image.ref=swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/flink:1.20.1-scala_2.12-java11 \
    -Dcontainerized.master.env.ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.20.1.jar \
    -Dcontainerized.taskmanager.env.ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-hadoop-1.20.1.jar \
    -Dkubernetes.artifacts.local-upload-enabled=true \
    -Dkubernetes.artifacts.local-upload-target=s3://dmetasoul-bucket/jiax/target \
    -Dkubernetes.artifacts.local-upload-overwrite=true \
    local:///home/jiax/toys/flink/first-love/target/first-love-0.1.jar

del:
    kubectl delete deployment my-first-application-cluster 

image version:
    docker build -t swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/flink-newbie:{{version}} .

push version:
    docker push swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/flink-newbie:{{version}}

logs:
    kubectl get pods | awk '$1 ~ /app/ {print $1}' |  awk '!(/task/ || /job/)' | xargs kubectl logs 

proxy:
    kubectl port-forward service/my-first-application-cluster-rest 8081

ls:
    mcli ls hwoss/dmetasoul-bucket/jiax/target

rm:
    mcli rm hwoss/dmetasoul-bucket/jiax/target/first-love-0.1.jar