set dotenv-load

app version: 
    flink run-application --target kubernetes-application \
    -Dkubernetes.cluster-id=my-first-application-cluster \
    -Dkubernetes.container.image.ref=swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/flink-newbie:{{version}} \
    local:///opt/flink/usrlib/first-love-0.1.jar

del:
    kubectl delete deployment my-first-application-cluster 

image version:
    docker build -t swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/flink-newbie:{{version}} .

push version:
    docker push swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/flink-newbie:{{version}}

logs:
    kubectl get pods | awk '$1 ~ /app/ {print $1}' |  awk '!(/task/ || /job/)' | xargs kubectl logs 

proxy:
    kubectl get pods | awk '$1 ~ /app/ {print $1}' | awk '!(/task/ || /job/)' | xargs -I {} kubectl port-forward {} 8992:8081

ls:
    aws s3 ls s3://dmetasoul-bucket/